### ISSUE TITLE
How to play?

### ISSUE THREAD

**Issue by chem-chikweze** [tiny-devs/tiny-dungeon-online#115]
It would be very helpful to put in help on how to play the game.

**Comment by diguifi** [comment]
you are right! i'll add that. but since we're already here, i'll sum it up:  
- arrow keys or WASD to move
- touch an enemy to start a fight
  - you can only hit one at a time, but they all can hit you at the same time
  - if you start a fight with some enemy, you can't fight any other before you kill the current enemy, unless you leave the room
  - enemies have levels, just like you, so becareful, the far south/east you move, the stronger the enemies are
  - enemies can drop coffee or gear
- to talk to an npc just move towards it
  - if a red text shows up, it means you started a quest (there are currently 2 and they are not yet saved, if you leave the game, they'll reset

**Comment by diguifi** [comment]
Hi! just added the "how to play button! 

[link](https://github.com/tiny-devs/tiny-dungeon-online/wiki/How-to-Play)
