### ISSUE TITLE
Move to Deno

### ISSUE THREAD

**Issue by FabriDamazio** [tiny-devs/tiny-dungeon-online#12]
We should consider move the project to Deno. What do you guys think?

**Comment by diguifi** [comment]
I think it's absolutely valid.  
We started the tiny dungeon idea back in june 2019 (almost a year ago), we had no clue where to begin, so we chose Node. A long time has passed since then and Deno has been proving to be the best choice as js runtime, also has native support for TS and WebSockets, which is just what we need.
